name: Continuos Delivery
on:
  push:
    branches:
      - main

jobs:
  Delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Deploy
        uses: actions/upload-artifact@v4
        with:
          name: proj.zip
          path: |
            "**.py"
            README.md
